INSERT INTO EMPLOYEE
VALUES (1, 29, 'Tumilowicz');

INSERT INTO EMPLOYEE
VALUES (2, 70, 'Mrozek');

INSERT INTO EMPLOYEE
VALUES (3, 82, 'Lem');

INSERT INTO EMPLOYEE
VALUES (4, 52, 'Hemingway');

COMMIT;